### ISSUE TITLE
Fix problem with font size on Pixel C [1-2h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Calculator#11]
Fix problem with font size on Pixel C when in horizontal orientation.

See discussion at https://literacyapp.slack.com/archives/team-development/p1477829634000002

**Comment by gscdev** [comment]
@jogrimst I have made changes for solve this error but I can't prove it. My Pixel C emulator doesn't work.

**Comment by jogrimst** [comment]
@gscdev The application crashed on Nexus 7 2013 (running CyanogenMod 13 / Android 6.0.1) when rotating from vertical orientation to horizontal orientation:

```java
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.literacyapp.calculator, PID: 28730
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.literacyapp.calculator/com.android.calculator2.Calculator}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.calculator2.view.MultiButton.setEnabled(int)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4121)
                      at android.app.ActivityThread.-wrap15(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5466)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.calculator2.view.MultiButton.setEnabled(int)' on a null object reference
                      at com.android.calculator2.Calculator$1.afterTextChanged(Calculator.java:101)
                      at com.android.calculator2.view.display.AdvancedDisplay$1.afterTextChanged(AdvancedDisplay.java:117)
                      at com.android.calculator2.view.display.AdvancedDisplay.setText(AdvancedDisplay.java:697)
                      at com.android.calculator2.Calculator.onCreate(Calculator.java:200)
                      at android.app.Activity.performCreate(Activity.java:6251)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4121) 
                      at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5466) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by jogrimst** [comment]
On Pixel C it did not crash when rotating to horizontal orientation, but the pads still look too small:

![screenshot_20161031-092208](https://cloud.githubusercontent.com/assets/1451036/19846015/38e56ebc-9f4d-11e6-829c-d15c269ad4a7.png)
